### ISSUE TITLE
Create a server deploy this html page and share webpage 

### ISSUE THREAD

**Issue by ParthasarathiPanda** [ParthasarathiPanda/Login-form#3]
Create a server deploy this html page and share webpage, add screenshot at the the time of submission.

**Comment by Partha-2000-Snp** [comment]
![image](https://github.com/ParthasarathiPanda/Login-form/assets/147611678/3ca05900-1cfe-4275-9805-9c3e323249e8)

Starting page name should be index.html in order to run it on web server.

![image](https://github.com/ParthasarathiPanda/Login-form/assets/147611678/878b4c2f-05c1-42df-85e0-48a12019b73b)

**Comment by Partha-2000-Snp** [comment]
![image](https://github.com/ParthasarathiPanda/Login-form/assets/147611678/d25b0607-dd5a-4125-87a1-d70f050d371d)

**Comment by ParthasarathiPanda** [comment]
Remove Geek for geeks add css

**Comment by Partha-2000-Snp** [comment]
![image](https://github.com/ParthasarathiPanda/Login-form/assets/147611678/da95daf9-f3b6-4167-8d87-5fa0f68ba235)

**Comment by ParthasarathiPanda** [comment]
completed
